<a href="https://colab.research.google.com/github/mrdo19111911/split-mini-/blob/main/split_mini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import math
import numpy as np
import numba 
from numba import njit


In [47]:
n =50
k = 5
location= np.random.randint(1, 1000000, (n,2))
# DM = np.empty((n,n, k), np.int_)
DM_veh = np.empty((n,n, k), np.int_)

for i in range(n):
    for j in range(n):
        DM_veh[i,j] =  round(math.sqrt(  ( location[i][0]-location[j][0] )**2+( location[i][1]-location[j][1] )**2)  *(k+1) ) 
        # DM_veh[i,j] =  round(1)
demand =  np.random.randint(1, 2, (n))
# DM_veh = np.empty((n,n, k), np.int_)


In [48]:
@njit
def create_virtual_graph(DM,demand,capacity):
    c = np.empty((n,n), np.int_)
    for i in range(n):
        for j in range(n):
            c[i,j]=10000000000
    for i in range(n):
        cost = 0
        demand_acc = 0
        c[i,i]=0
        for j in range(i+1,n-1):
            if j==i+1:
                cost= DM[0][i+1]
            else:
                cost += DM[j-1][j]
            demand_acc+= demand[j]
            if demand_acc>capacity:
                # c[i,j]=0
                break
            else:
                c[i,j]= cost +DM[j][0]
    return c
DM =  DM_veh[1]
all_c=[]
for _ in range(k):
    all_c.append(create_virtual_graph(DM, demand,6))
# c = create_virtual_graph(DM, demand, 2000000)


# for x in c:
#     print(x)

In [49]:

item = all_c[3]
for i in range(len(item)):
    for j in range(i+1,len(item)):
        if item[i,j]<100000000:
            print(i,j,item[i,j])

0 1 5392207
0 2 8798661
0 3 10562663
0 4 14041217
0 5 15195171
0 6 17164585
1 2 8798661
1 3 10562663
1 4 14041217
1 5 15195171
1 6 17164585
1 7 17376659
2 3 7156209
2 4 10634763
2 5 11788717
2 6 13758131
2 7 13970205
2 8 23295991
3 4 8870761
3 5 10024715
3 6 11994129
3 7 12206203
3 8 21531989
3 9 27062937
4 5 2316254
4 6 4285668
4 7 4497742
4 8 13823528
4 9 19354476
4 10 16797538
5 6 2142834
5 7 2354908
5 8 11680694
5 9 17211642
5 10 14654704
5 11 20088738
6 7 1177454
6 8 10503240
6 9 16034188
6 10 13477250
6 11 18911284
6 12 19663296
7 8 5251620
7 9 10782568
7 10 8225630
7 11 13659664
7 12 14411676
7 13 13931438
8 9 5391284
8 10 2834346
8 11 8268380
8 12 9020392
8 13 8540154
8 14 16579463
9 10 3668170
9 11 9102204
9 12 9854216
9 13 9373978
9 14 17413287
9 15 26047290
10 11 5979084
10 12 6731096
10 13 6250858
10 14 14290167
10 15 22924170
10 16 27288390
11 12 6529574
11 13 6049336
11 14 14088645
11 15 22722648
11 16 27086868
11 17 30961796
12 13 3607976
12 14 11647285
12 15 20281288
12

In [61]:
@njit
def find_shortest_path(c):
    price= np.zeros((n), np.int_)
    pred = np.zeros((n), np.int_)
    for i in range(1,n):
       price[i]= 100**6 
    for i in range(len(c)-1):
        j = i + 1
        # print(i,j)

        while j < len(c) and c[i][j]<100000000:
            # temp= np.zeros((n), np.int_)
            # print(price[i] ,c[i][j], price [j])

            if price[i] + c[i][j] <= price [j]:
                price[j] = price[i] + c[i][j]
                pred[j] = i
            j+=1

        temp = [ x if x < 1000000 else -1 for x in price ]
        


    return price, pred

price, pred = find_shortest_path(all_c[3])
price, pred 

(array([            0,       5392207,       8798661,      10562663,
             14041217,      15195171,      17164585,      17550079,
             22801699,      28192983,      25636045,      31070079,
             31822091,      31341853,      37189667,      44753140,
             49117360,      52992288,      56060533,      57906396,
             62658941,      67779189,      73662374,      77759376,
             81898847,      88520267,      88491279,      93869670,
             97466059,     102956018,     108587937,     110041728,
            118448890,     116233324,     125597658,     127107733,
            130969665,     133749580,     135198788,     140487841,
            147057776,     150236337,     152970631,     152587074,
            159169811,     162113902,     163913704,     167213087,
            168912884, 1000000000000]),
 array([ 0,  0,  0,  0,  0,  0,  0,  5,  7,  8,  8,  8,  8,  8, 13, 14, 14,
        14, 14, 14, 14, 19, 21, 21, 21, 21, 21, 21, 27, 27, 27, 27, 

In [62]:
route=[]

for i in range(len(pred)):
    if i==0:
        route.append(0)
        continue 
    if pred[i]!= pred[i-1]:
        route.append(i-1)

route

[0, 6, 7, 8, 13, 14, 20, 21, 27, 31, 33, 39, 44, 45, 48]

In [63]:
price

array([            0,       5392207,       8798661,      10562663,
            14041217,      15195171,      17164585,      17550079,
            22801699,      28192983,      25636045,      31070079,
            31822091,      31341853,      37189667,      44753140,
            49117360,      52992288,      56060533,      57906396,
            62658941,      67779189,      73662374,      77759376,
            81898847,      88520267,      88491279,      93869670,
            97466059,     102956018,     108587937,     110041728,
           118448890,     116233324,     125597658,     127107733,
           130969665,     133749580,     135198788,     140487841,
           147057776,     150236337,     152970631,     152587074,
           159169811,     162113902,     163913704,     167213087,
           168912884, 1000000000000])